name: build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - "project/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: cache playwright
        id: playwright-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: pw-new-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Bootstrap packages
        run: npm run bootstrap

      - name: Lint packages
        run: npm run lint
        env:
          CI: true

      - name: Build packages
        run: npm run build
        env:
          CI: true

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1.4.0
        with:
          keep_history: true
          target-branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Run server
        run: npm run start:built & npx wait-on http://localhost:3000
        env:
          CI: true

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
